### ISSUE TITLE
XDG Data directories...

### ISSUE THREAD

**Issue by 3v1n0** [ubuntu/snapcraft-desktop-helpers#23] opened 2016-11-14 18:35 UTC
Would be the case to define a `~/.config/user-dirs.dirs` file that points to the $HOST_HOME dirs if home interface has been set?

The problem is that we can't read the real user settings for that, so probably we'd need some snap-launcher features.

**Comment by didrocks** [comment] 2016-11-15 07:37
What I did for that case it rather doing symlinks (look at the dconf example=. That protects us and keep all data in a single directory, under a SNAP revision, which will ideally be the long term "exposure" for those data once we get the interfaces. I think we should continue following that trend

**Comment by didrocks** [comment] 2017-02-17 11:24
Is that still an issue for you or the env variables we now exports fixes all your use cases?

**Comment by 3v1n0** [comment] 2017-02-17 11:48
Well, still I don't see the various `$XDG_xxx_DIR` defined...

In a snapped gtk app I've done, for some reason I only see the "Video" folder in the file selector to be valid, while others aren't. But I guess that creating a dummy dirs files with `xdg-user-dirs-update --force --dummy-output`, replace the `$HOME` in there with the actual host home, and see if these paths are readable, and in case change the values in `~/.config/user-dirs.dirs` is something that can work properly in most systems.

**Comment by lapisdecor** [comment] 2017-12-08 00:12
I'm not sure if this is related to my own issue, but I've created a snap with python3 and python3-gi and when I run it, it tries to create home/user/ default subdirs. The problem is, they are created on the system if I have the home plug. and I get duplicate directories in my own language, and the new ones, in English. My program only opens a window. Nothing else. Without the home plug it tries to write the subdirectories, but can't.

Source of my program is here: [hellowayland](https://github.com/lapisdecor)/hellowayland

**Comment by kenvandine** [comment] 2018-04-18 16:27
This should be resolved now, since #103 was merged, we now read the users user-dirs and honor them.

**Closed by kenvandine** 2018-04-18 16:27 UTC
